# Generated by Django 3.1.7 on 2021-05-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('idBat', models.UUIDField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=200)),
                ('sobreviviente', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Hechizo',
            fields=[
                ('nombreH', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('puntosDH', models.IntegerField()),
            ],
            options={
                'ordering': ['nombreH'],
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('idP', models.UUIDField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=200)),
                ('razaP', models.CharField(max_length=200)),
                ('puntosSaludP', models.IntegerField()),
            ],
            options={
                'ordering': ['nombreP'],
            },
        ),
        migrations.CreateModel(
            name='TipoDD',
            fields=[
                ('nombreD', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['nombreD'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('idPar', models.UUIDField(primary_key=True, serialize=False)),
                ('deb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_deb', to='SkyrimApp.tipodd')),
                ('inf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_inf', to='SkyrimApp.tipodd')),
            ],
        ),
        migrations.CreateModel(
            name='Bestia',
            fields=[
                ('particiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SkyrimApp.participante')),
                ('nombreB', models.CharField(max_length=200)),
                ('razaB', models.CharField(max_length=200)),
                ('puntosDB', models.IntegerField()),
                ('puntosSB', models.IntegerField()),
            ],
            options={
                'ordering': ['nombreB'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hechizo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='SkyrimApp.hechizo')),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='SkyrimApp.participante')),
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='SkyrimApp.personaje')),
            ],
            options={
                'ordering': ['participante'],
                'unique_together': {('participante', 'personaje', 'hechizo')},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noE', models.IntegerField()),
                ('saludDA', models.IntegerField()),
                ('idDam', models.IntegerField()),
                ('idAt', models.IntegerField()),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_batalla', to='SkyrimApp.batalla')),
                ('hlanzado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_from', to='SkyrimApp.hechizo')),
                ('participante1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_par1', to='SkyrimApp.participante')),
                ('participante2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_par2', to='SkyrimApp.participante')),
            ],
            options={
                'ordering': ['batalla'],
                'unique_together': {('participante1', 'participante2', 'batalla')},
            },
        ),
    ]
