# Generated by Django 3.1.7 on 2021-05-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batalla',
            name='idBat',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='idPar',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
