# Generated by Django 3.1.7 on 2021-05-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0002_auto_20210525_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['participante'], 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='tipodd',
            options={'ordering': ['nombreD'], 'verbose_name': 'Tipo de Daño', 'verbose_name_plural': 'Tipos de Daño'},
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='nombreH',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='puntosDH',
            field=models.IntegerField(verbose_name='Puntos de Daño'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='deb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_deb', to='SkyrimApp.tipodd', verbose_name='Debilidad'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='idPar',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='inf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_inf', to='SkyrimApp.tipodd', verbose_name='Daño'),
        ),
    ]
