# Generated by Django 3.1.7 on 2021-05-26 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0004_auto_20210525_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batalla',
            name='sobreviviente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobreviviente', to='SkyrimApp.participante'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='batalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='SkyrimApp.batalla'),
        ),
    ]
