# Generated by Django 3.1.7 on 2021-05-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0005_auto_20210525_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='idAt',
            field=models.IntegerField(verbose_name='ID del Atacante'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idDam',
            field=models.IntegerField(verbose_name='ID del Damnificado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='noE',
            field=models.IntegerField(verbose_name='Número de Evento'),
        ),
    ]
