# Generated by Django 3.1.7 on 2021-05-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0006_auto_20210525_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='batalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='SkyrimApp.batalla', verbose_name='Batalla'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hlanzado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_from', to='SkyrimApp.hechizo', verbose_name='Hechizo Lanzado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='saludDA',
            field=models.IntegerField(verbose_name='Salud del Atacante'),
        ),
    ]
