# Generated by Django 3.1.7 on 2021-05-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0007_auto_20210525_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='idAt',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='idDam',
        ),
    ]
