# Generated by Django 3.1.7 on 2021-05-26 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0008_auto_20210525_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='batalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='SkyrimApp.batalla', verbose_name='Batalla'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hlanzado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='SkyrimApp.hechizo', verbose_name='Hechizo Lanzado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participante1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_ganados', to='SkyrimApp.participante', verbose_name='Atacante'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participante2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_perdidos', to='SkyrimApp.participante', verbose_name='Damnificado'),
        ),
    ]
