# Generated by Django 3.1.7 on 2021-05-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0009_auto_20210525_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='participante1',
            new_name='atacante',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='participante2',
            new_name='damnificado',
        ),
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together={('atacante', 'damnificado', 'batalla')},
        ),
    ]
