# Generated by Django 3.1.7 on 2021-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0010_auto_20210525_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='idP',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
