# Generated by Django 3.1.7 on 2021-05-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0011_auto_20210527_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestia',
            old_name='particiante',
            new_name='participante',
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombreP',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='razaP',
            field=models.CharField(max_length=200, verbose_name='Raza'),
        ),
    ]
