# Generated by Django 3.1.7 on 2021-05-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0012_auto_20210527_1745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jugador',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='hechizo',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='personaje',
        ),
        migrations.DeleteModel(
            name='Bestia',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
