# Generated by Django 3.1.7 on 2021-05-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyrimApp', '0013_auto_20210527_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestia',
            fields=[
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SkyrimApp.participante')),
                ('nombreB', models.CharField(max_length=200)),
                ('razaB', models.CharField(max_length=200)),
                ('puntosDB', models.IntegerField()),
                ('puntosSB', models.IntegerField()),
            ],
            options={
                'ordering': ['nombreB'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hechizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='SkyrimApp.hechizo')),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='SkyrimApp.participante')),
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='SkyrimApp.personaje')),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
                'ordering': ['participante'],
                'unique_together': {('participante', 'personaje', 'hechizo')},
            },
        ),
    ]
